services:
  db:
    image: postgis/postgis
    container_name: postgis_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: local
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./drizzle/:/docker-entrypoint-initdb.d

volumes:
  postgres-data:
